on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo 'Hello World XYZ'
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
